# Generated by Django 3.2.18 on 2023-04-20 03:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caprofile',
            name='office_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_ca',
            field=models.BooleanField(default=False, verbose_name='Is CA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False, verbose_name='Is User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, choices=[('DELHI_NCR', 'Delhi NCR'), ('BHOPAL', 'Bhopal'), ('INDORE', 'Indore'), ('UP', 'Uttar Pradesh'), ('PUNJAB', 'Punjab'), ('RAJASTHAN', 'Rajasthan')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location_pref',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DELHI_NCR', 'Delhi NCR'), ('BHOPAL', 'Bhopal'), ('INDORE', 'Indore'), ('UP', 'Uttar Pradesh'), ('PUNJAB', 'Punjab'), ('RAJASTHAN', 'Rajasthan')], max_length=64, null=True),
        ),
    ]
