# Generated by Django 3.2.18 on 2023-04-23 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaServicesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=120)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caservice.caservice')),
            ],
            options={
                'unique_together': {('service', 'ca')},
                'index_together': {('service', 'ca')},
            },
        ),
    ]
