# Generated by Django 3.2.18 on 2023-04-24 08:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('caservice', '0002_caservicesprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='caservice',
            name='features',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
