# Generated by Django 3.2.18 on 2023-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caservice', '0003_caservice_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caservice',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
